language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
  - PACKAGE=cryptohash.0.2
  matrix:
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      env: OCAML_VERSION=4.03
    - os: linux
      env: OCAML_VERSION=4.04
